package com.kun.app.operater.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class Operater {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column operater.id
	 * 
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column operater.name
	 * 
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column operater.password
	 * 
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column operater.status
	 * 
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column operater.id
	 * 
	 * @return the value of operater.id
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column operater.id
	 * 
	 * @param id
	 *            the value for operater.id
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column operater.name
	 * 
	 * @return the value of operater.name
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column operater.name
	 * 
	 * @param name
	 *            the value for operater.name
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column operater.password
	 * 
	 * @return the value of operater.password
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	@JsonIgnore
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column operater.password
	 * 
	 * @param password
	 *            the value for operater.password
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column operater.status
	 * 
	 * @return the value of operater.status
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column operater.status
	 * 
	 * @param status
	 *            the value for operater.status
	 * @mbggenerated Thu Apr 24 23:56:12 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}